oss-review-toolkit/ort-config

- tools/curation-generator/build.gradle.kts
> Miscellaneous small improvements

- curations/NuGet/_/Log4ALA.yml
- curations/NuGet/_/Microsoft.AspNet.WebApi.Client.yml
- curations/NuGet/_/Microsoft.NETCore.Platforms.yml
- curations/NuGet/_/System.Memory.Data.yml
Some curations for NuGet packages, see the commit messages for details.
> NuGet curations

- .github/CODEOWNERS
> Add an initial CODEOWNERS file to automate assignment of reviewers

- README.md
- asciidoctor-pdf-theme.yml
- evaluator-rules/build.gradle.kts
- evaluator-rules/src/main/resources/example.rules.kts
- license-classifications.yml
- notifications/build.gradle.kts
- notifications/src/main/resources/example.notifications.kts
- packages/Gem/_/execjs/2.7.0/vcs.yml
- packages/Gem/_/execjs/2.8.0/vcs.yml
- packages/Gem/_/execjs/2.8.1/vcs.yml
- packages/GoMod/_/github.com%2Fgorilla%2Fmux/v1.7.2/vcs.yml
- packages/GoMod/_/github.com%2Fgorilla%2Fmux/v1.8.0/vcs.yml
- packages/GoMod/_/github.com%2Fspf13%2Fcobra/v1.0.0/vcs.yml
- packages/GoMod/_/github.com%2Fspf13%2Fcobra/v1.2.1/vcs.yml
- packages/GoMod/_/github.com%2Fspf13%2Fcobra/v1.3.0/vcs.yml
- packages/GoMod/_/github.com%2Fspf13%2Fpflag/v1.0.3/vcs.yml
- packages/GoMod/_/github.com%2Fspf13%2Fpflag/v1.0.5/vcs.yml
- resolutions.yml
See individual commits for details
> Add new config files

- curations/Maven/com.vladsch.flexmark/flexmark-all.yml
> Add a VCS curation for "Maven:com.vladsch.flexmark:flexmark-all:0.34.30"

- README.md
- curations/PyPI/_/asgiref.yml
- curations/PyPI/_/astroid.yml
- curations/PyPI/_/click.yml
- curations/PyPI/_/fakeredis.yml
- curations/PyPI/_/idna.yml
- curations/PyPI/_/lazy-object-proxy.yml
- curations/PyPI/_/packaging.yml
- curations/PyPI/_/pycparser.yml
- curations/PyPI/_/starlette.yml
- curations/PyPI/_/uvicorn.yml
- curations/PyPI/_/wrapt.yml
- tools/curations/build.gradle.kts
Allow and add several declared license mappings. See the commit messages for details.
> Declared license mappings

- curations/Maven/org.eclipse.sw360/client.yml
- curations/Maven/org.eclipse.sw360/http-support.yml
Note: This is the sw360 client version used in ORT.
> curations: Curate VCS revision for sw360 clients version 3.2.0-28

- curations/NuGet/_/log4net.yml
> Add a VCS curation for "NuGet::log4net:2.0.8"

- curations/NuGet/_/log4net.yml
> curations: Add VCS URLs for log4net

- .github/workflows/verification.yml
- tools/curations/build.gradle.kts
- tools/curations/buildSrc/src/main/kotlin/Utils.kt
- tools/curations/buildSrc/src/main/kotlin/VerifyPackageConfigurationsTask.kt
- tools/curations/buildSrc/src/main/kotlin/VerifyPackageCurationsTask.kt
See the commit messages for details.
> Add verification for package configurations

- curations/Maven/com.typesafe.sbteclipse/sbteclipse-plugin.yml
- curations/Maven/com.vladsch.flexmark/flexmark-all.yml
- curations/NuGet/_/log4net.yml
- curations/PyPI/_/j1939.yml
> Add a curation specifically for version "0.1.0.dev1" of "PyPI::j1939" 

- evaluator-rules/src/main/resources/example.rules.kts
- license-classifications.yml
Please see individual commits for details.
Note: This is only part 1 of improving the rules, will submit part 2 when this PR is merged.
> Improve example rules

- curations/Maven/com.amazonaws/aws-java-sdk.yml
See https://github.com/aws/aws-sdk-java.
> curations: Add metadata only curation for aws-java-sdk

- package-configurations/Go/_/github.com%2Fgorilla%2Fmux/v1.7.2/vcs.yml
- package-configurations/Go/_/github.com%2Fgorilla%2Fmux/v1.8.0/vcs.yml
- package-configurations/Go/_/github.com%2Fspf13%2Fcobra/v1.0.0/vcs.yml
- package-configurations/Go/_/github.com%2Fspf13%2Fcobra/v1.2.1/vcs.yml
- package-configurations/Go/_/github.com%2Fspf13%2Fcobra/v1.3.0/vcs.yml
- package-configurations/Go/_/github.com%2Fspf13%2Fpflag/v1.0.3/vcs.yml
- package-configurations/Go/_/github.com%2Fspf13%2Fpflag/v1.0.5/vcs.yml
See https://github.com/oss-review-toolkit/ort/pull/5546.
> Align with using "Go" as `Identifier.type` for Go packages

- evaluator-rules/src/main/resources/example.rules.kts
See individual commits for details.
> Minor fixes

- package-configurations/NPM/_/async/2.6.1/vcs.yml
- package-configurations/NPM/_/async/3.1.1/vcs.yml
- package-configurations/NPM/_/async/3.2.0/vcs.yml
- package-configurations/NPM/_/async/3.2.1/vcs.yml
- package-configurations/NPM/_/async/3.2.2/vcs.yml
- package-configurations/NPM/_/async/3.2.3/vcs.yml
- package-configurations/NPM/_/async/3.2.4/vcs.yml
Signed-off-by: Shruti Dadoo <shruti.dadoo@here.com>
> package-configurations: Add various versions of async packages

- evaluator-rules/src/main/resources/example.rules.kts
Done in context of my work on https://github.com/oss-review-toolkit/ort/issues/5621,
> example-rules: Refactor for consistency and readability

- evaluator-rules/build.gradle.kts
- evaluator-rules/gradle.properties
- evaluator-rules/gradle/libs.versions.toml
- notifications/build.gradle.kts
- notifications/gradle.properties
- notifications/gradle/libs.versions.toml
- tools/curations/buildSrc/build.gradle.kts
- tools/curations/buildSrc/settings.gradle.kts
- tools/curations/gradle/libs.versions.toml
> Migrate to Gradle version catalogs

- evaluator-rules/gradle/libs.versions.toml
- evaluator-rules/src/main/resources/example.rules.kts
- notifications/gradle/libs.versions.toml
- tools/curations/gradle/libs.versions.toml
> Upgrade ORT to adapt for rules API changes

- evaluator-rules/src/main/resources/evaluator.rules.kts
> evaluator.rules: Several improvements

- evaluator-rules/src/main/resources/evaluator.rules.kts
Note: Must be merged after https://github.com/oss-review-toolkit/ort/pull/6082.
> Evaluator rules improvements

- evaluator-rules/src/main/resources/evaluator.rules.kts
> Violation message improvements

- evaluator-rules/src/main/resources/evaluator.rules.kts
> rules: Handle license categories 'proprietary-free' and 'free-restricted'

- evaluator-rules/src/main/resources/evaluator.rules.kts
> Vulnerability rule naming / improvements

- README.md
Signed-off-by: Sebastian Schuberth <sschuberth@gmail.com>
> README: Link to ORT's configuration files section

- how-to-fix-text-provider.kts
- notifications/src/main/resources/example.notifications.kts
See https://github.com/oss-review-toolkit/ort/pull/6415.
Note: **Must be merged after https://github.com/oss-review-toolkit/ort/pull/6415.**
> refactor: Align with the renaming of OrtIssue

- curations/Maven/com.amazonaws/aws-java-sdk.yml
- curations/Maven/io.netty/netty-all.yml
- curations/Maven/io.netty/netty-tcnative-boringssl-static.yml
Align with [^1].
[^1]: https://github.com/oss-review-toolkit/ort/commit/b9e8b63ace7215f042a80b41f5c8b5fcbedaebea
> refactor(curations): Eliminate the use of a legacy property name

- evaluator-rules/src/main/resources/evaluator.rules.kts
> Miscellanoues minor fixes

- tools/curations/buildSrc/src/main/kotlin/ScanCodeLicenseDbClassifications.kt
> Fix crashing scancode license import

- evaluator-rules/src/main/resources/evaluator.rules.kts
- license-classifications.yml
> Update license classifications from ScanCode licensedb

- license-classifications.yml
- tools/curations/buildSrc/src/main/kotlin/ScanCodeLicenseDbClassifications.kt
> Categorize several pairs of GPL licenses with exceptions

- .github/workflows/verification.yml
- tools/curations/buildSrc/build.gradle.kts
- tools/curations/buildSrc/src/main/kotlin/GenerateAspNetCoreCurationsTask.kt
- tools/curations/buildSrc/src/main/kotlin/GenerateAwsSdkForNetCurationsTask.kt
- tools/curations/buildSrc/src/main/kotlin/GenerateAzureSdkForNetCurationsTask.kt
- tools/curations/buildSrc/src/main/kotlin/GenerateDotNetRuntimeCurationsTask.kt
- tools/curations/gradle/libs.versions.toml
See [1] for the list of changes.
[1]: https://github.com/oss-review-toolkit/ort/compare/7df497b47b...1.0.1
> build: Switch to official ORT release 1.0.1

- tools/curations/gradle/libs.versions.toml
For the changes see [1].
[1]: https://github.com/oss-review-toolkit/ort/compare/3.0.0...6.0.0
> deps: Upgrade to ORT 6.0.0

- gradle/libs.versions.toml
- tools/curations/gradle/libs.versions.toml
See [1].
[1]: https://github.com/oss-review-toolkit/ort/releases/tag/7.0.0
> deps: Upgrade to ORT 7.0.0

- curations/Maven/bsf/bsf.yml
- curations/Maven/commons-cli/commons-cli.yml
> Account for some Apache projects having moved from Subversion to GitHub

- tools/curations/gradle/libs.versions.toml
For the changes see [1].
[1]: https://github.com/oss-review-toolkit/ort/compare/7.0.0...9.0.0
> deps: Upgrade to ORT 11.0.0

- curations/Maven/com.martiansoftware/jsap.yml
- curations/Maven/commons-logging/commons-logging-api.yml
> Add two curations for Maven packages

- .github/workflows/verification.yml
- gradle/libs.versions.toml
- tools/curations/gradle/libs.versions.toml
> Miscellaneous CI updates

- curations/Maven/androidx.hilt/_.yml
- curations/Maven/androidx.legacy/_.yml
> Generalize a couple of `sourceCodeOrigins` curations to apply to the whole namespace

- gradle/libs.versions.toml
- tools/curations/gradle/libs.versions.toml
See [1].
[1]: https://github.com/oss-review-toolkit/ort/releases/tag/22.3.0
> deps: Upgrade to ORT 22.3.0

- evaluator.rules.kts
> Miscellaneous rules improvements

- evaluator.rules.kts
See individual commits for details.
> Various minor fixes for the Evaluator rules

- curations/NuGet/Dirkster/MLib.yml
- curations/NuGet/Dirkster/WatermarkControlsLib.yml
> Set the VCS revision for Dirkster NuGet packages

- curations/NuGet/Extended.Wpf/Toolkit.yml
> Set the VCS revision for Extended.Wpf:Toolkit NuGet package

- curations/NuGet/_/SharpSvn.1.9-x64.yml
> Set the VCS info for SharpSvn.1.9-x64 NuGet package

- evaluator.rules.kts
See [1].
[1]: https://github.com/oss-review-toolkit/ort/pull/9091
> fix(rules): Adjust to the new vulnerability API
