- curations/NuGet/_/ncrontab.signed.yml
The package was renamed to use uppercase with the latest release 3.3.2,
but all curations affect the previous versions where the lowercase name
was used.
> curations: Change NuGet::NCrontab.Signed to NuGet::ncrontab.signed

- curations/Maven/com.typesafe.sbteclipse/sbteclipse-plugin.yml
> Add a VCS curation for "Maven:com.typesafe.sbteclipse:sbteclipse-plugin"

- curations/Maven/bsf/bsf.yml
See [1].
[1]: https://commons.apache.org/proper/commons-bsf/source-repository.html
> Add a VCS curation for "Maven:bsf:bsf"

- curations/Maven/com.github.klangfarbe/statechart.yml
> Add a VCS curation for "Maven:com.github.klangfarbe:statechart"

- curations/PyPI/_/j1939.yml
This is specifically for `PyPI::j1939:0.1.0.dev1` as `v0.1.0-dev1` is
the only tag in the repository.
> Add a VCS URL curation for the `j1939` PyPI package

- package-configurations/Go/_/github.com%2Fgorilla%2Fmux/1.7.2/vcs.yml
- package-configurations/Go/_/github.com%2Fgorilla%2Fmux/1.8.0/vcs.yml
- package-configurations/Go/_/github.com%2Fspf13%2Fcobra/1.0.0/vcs.yml
- package-configurations/Go/_/github.com%2Fspf13%2Fcobra/1.2.1/vcs.yml
- package-configurations/Go/_/github.com%2Fspf13%2Fcobra/1.3.0/vcs.yml
- package-configurations/Go/_/github.com%2Fspf13%2Fpflag/1.0.3/vcs.yml
- package-configurations/Go/_/github.com%2Fspf13%2Fpflag/1.0.5/vcs.yml
The versions have been normalized to be valid semver versions, see also
https://github.com/oss-review-toolkit/ort/pull/5586 and https://github.com/oss-review-toolkit/ort/issues/5532.
> Re-align the version strings for Go packages

- evaluator-rules/src/main/resources/example.rules.kts
The evaluator injects the (top-level) property named `ortResult` into
the policy rules script aka `rules.kts`. Align on always using that
property for accessing the `OrtResult` instance.
Note: This was spotted in context of https://github.com/oss-review-toolkit/ort/issues/5621.
> example.rules.kts: Access the given `OrtResult` in a single way

- evaluator-rules/src/main/resources/example.rules.kts
Consistently use 'Rule' as suffix for rule creation functions.
> example-rules: Rename two functions for consistency

- evaluator-rules/src/main/resources/example.rules.kts
The evaluator rules in this repository have been created based on ORT's example policy rules, meanwhile they deviated, but are quite redundant. Reduce the deviation use-case-wise by copying all rules from ORT's examples which are missing in this repository using ORT revision [1].
This is the first step towards making the 'ort-config' repository the single dedicated place to examplify policy rules. In the following ORT's example rules will be deleted, or rather minimized and turned into functional test assets, see also [2].
Note: The copied rules have been created as part of [3].
[1] 63e002ba57e7d49c96017fac2ff679de8a5b76df
[2] https://github.com/oss-review-toolkit/ort/issues/5701 
[3] https://github.com/oss-review-toolkit/ort/issues/5621
Part of: …
> evaluator-rules: Pull in all missing rules from ORT's example rules

- evaluator-rules/src/main/resources/example.rules.kts
Further illustrate the "prior to open sourcing" use case.
Part of: https://github.com/oss-review-toolkit/ort/issues/5621.
Note: **Must be merged after** https://github.com/oss-review-toolkit/ort/pull/5823.
> Add further rules using file checks

- license-classifications.yml
The categories 'copyleft' and 'strong-copyleft' have identical semantics, while 'copyleft' has more usages and aligns with ScanCode's category name. So, align on using 'copyleft' as category for "Strong Copyleft" licenses.
Part of #59.
> license-classification: Drop the redundant 'strong-copyleft' category

- tools/curations/buildSrc/src/main/kotlin/AbstractGenerateCurationsTask.kt
- tools/curations/buildSrc/src/main/kotlin/BaseGenerateCurationsTask.kt
- tools/curations/buildSrc/src/main/kotlin/GenerateAspNetCoreCurationsTask.kt
- tools/curations/buildSrc/src/main/kotlin/GenerateAzureSdkForNetCurationsTask.kt
- tools/curations/buildSrc/src/main/kotlin/GenerateDotNetRuntimeCurationsTask.kt
- tools/curations/buildSrc/src/main/kotlin/VerifyPackageConfigurationsTask.kt
- tools/curations/buildSrc/src/main/kotlin/VerifyPackageCurationsTask.kt
These tasks don't need to be abstract as they don't have any abstract functions. So, drop the `abstract` keyword in favor of `open`, as Gradle tasks are required to be non-final.
> tools/curations: Make several Gradle tasks non-abstract

- evaluator-rules/src/main/resources/example.rules.kts
Compilation started to fail as of [1].
[1] https://github.com/oss-review-toolkit/ort-config/commit/35faef661e70c4b81d130ce5afb3eb8de86c62e3
> evaluator-rules: Fix-up a compilation error

- package-configurations/NPM/_/spdx-correct/3.1.0/vcs.yml
- package-configurations/NPM/_/spdx-exceptions/2.2.0/vcs.yml
- package-configurations/NPM/_/spdx-license-ids/3.0.5/vcs.yml
- package-configurations/NPM/_/v8-compile-cache/2.1.0/vcs.yml
Fix violations in 4 packages which cause a high amount of false positives, to reduce the amount of errors quite a bit.
> Fix a couple of rule violations for the `mime-types` example scan

- evaluator-rules/gradle/libs.versions.toml
- evaluator-rules/src/main/resources/example.rules.kts
- license-classifications.yml
- notifications/gradle/libs.versions.toml
- tools/curations/build.gradle.kts
- tools/curations/buildSrc/src/main/kotlin/GenerateLicenseClassificationsTask.kt
- tools/curations/buildSrc/src/main/kotlin/ScanCodeLicenseDbClassifications.kt
- tools/curations/gradle/libs.versions.toml
Add a Gradle task which generates `license-classifications.yml` from ScanCode's license data hosted at `aboutcode.org` and make use of the generated file.
Fixes #59.
Note: As a follow up, policy rules will need to be extended to handle new license categories.
For now, the newly added categories will still be flagged by the evaluator rule `UNHANDLED_LICENSE`.
> Switch to a generated `license-classifications.yml` based on ScanCode's License DB

- evaluator-rules/src/main/resources/evaluator.rules.kts
Drop the copy pasted mention of "ORT examples", make the disclaimer a bit more prominent and avoid using the term example overall while still making clear that no legal recommendation is made. While at it wrap it at 80 chars.
> evaluator-rules: Improve the disclaimer a bit

- evaluator-rules/src/main/resources/evaluator.rules.kts
Treat excluded copyleft (limited) licenses as not applicable.
> evaluator.rules: Make the copyleft (limited) rules adhere to excludes

- evaluator-rules/src/main/resources/evaluator.rules.kts
It does not matter in which tree level the license is found.
Context: #66.
> evaluator.rules: Apply the copyleft limited rule to any tree level

- evaluator-rules/src/main/resources/evaluator.rules.kts
This is a fix-up for 87c2049e329148390c524b82ddea460cf0cb4375.
Context: #66.
> evaluator.rules: Add 'free-restricted' to handled licenses

- evaluator-rules/src/main/resources/evaluator.rules.kts
- license-classifications.yml
- tools/curations/buildSrc/src/main/kotlin/ScanCodeLicenseDbClassifications.kt
Context #66.
Note: I've proposed the corresponding extension of ScanCode's license data model here: https://github.com/nexB/scancode-toolkit/issues/3147.
> Gracefully handle Contributor License Agreements

- evaluator-rules/src/main/resources/evaluator.rules.kts
- tools/curations/buildSrc/src/main/kotlin/ScanCodeLicenseDbClassifications.kt
> evaluator.rules: Add handling for further license categories

- evaluator-rules/src/main/resources/evaluator.rules.kts
This is a fix-up for 3c394bc8fdc16af63d867fc6bcc92a002a1d40ac.
Context: #66.
> evaluator.rules: Add a missing `-isExcluded()`

- evaluator-rules/src/main/resources/evaluator.rules.kts
> evaluator.rules: Improve the copyleft in source rules

- NOTICE
- README.md
- evaluator-rules/build.gradle.kts
- evaluator-rules/src/main/resources/evaluator.rules.kts
- how-to-fix-text-provider.kts
- notice/by-package.ftl
- notice/summary.ftl
- notifications/build.gradle.kts
- notifications/src/main/resources/example.notifications.kts
As agreed upon in [1].
[1]: https://github.com/oss-review-toolkit/ort-governance/issues/6
> Use the new copyright statement in all files

- license-classifications.yml
- tools/curations/buildSrc/src/main/kotlin/ScanCodeLicenseDbClassifications.kt
> license-classifications: Improve what gets assigned to the 'include-in-notice-file' category

- evaluator-rules/gradle/libs.versions.toml
- notifications/gradle/libs.versions.toml
- tools/curations/gradle/libs.versions.toml
This fixes the security vulnerability CVE-2022-42003, see: [1]. Full changes can be found here [2].
[1]: https://nvd.nist.gov/vuln/detail/CVE-2022-42003
[2]: https://github.com/oss-review-toolkit/ort/compare/e8c786d3bb...7aa61bf96b
> Gradle: Update ORT to 7aa61bf96b

- .ort.yml
These projects are not used for distribution, and can therefore be excluded.
> ort.yml: Add exclusions for example and tool projects

- evaluator-rules/gradle/libs.versions.toml
- notifications/gradle/libs.versions.toml
- tools/curations/buildSrc/build.gradle.kts
- tools/curations/buildSrc/src/main/kotlin/Utils.kt
- tools/curations/buildSrc/src/main/kotlin/VerifyPackageCurationsTask.kt
- tools/curations/gradle/libs.versions.toml
A preceeding change renamed the notice template files, which was done to align with ORT's recent refactoring of the
`PlainTextTemplateReporter`, formerly called `NoticeTemplateReporter`.
Upgrade ORT to have this `PlainTextTemplateReporter` available.
> deps(Gradle): Upgrade ORT to version e50456588d

- tools/curations/buildSrc/src/main/kotlin/ScanCodeLicenseDbClassifications.kt
This is part of #107 .
Note: The regeneration of `license-classifications.yml` needs to be deferred until https://github.com/nexB/scancode-licensedb/issues/35 is fixed and will be done in a separate PR.
> Align license classification generation with recent ScanCode `licensedb` changes

- tools/curations/buildSrc/src/main/kotlin/ScanCodeLicenseDbClassifications.kt
> fix(tools/curations): Make `LicenseDetails.text` nullable

- evaluator-rules/src/main/resources/evaluator.rules.kts
- license-classifications.yml
- tools/curations/buildSrc/src/main/kotlin/ScanCodeLicenseDbClassifications.kt
Make classifications from latest and greatest ScanCode licensedb work in ORT with older ScanCode versions.
> License classifications backwards compatibility

- tools/curations/buildSrc/src/main/kotlin/ScanCodeLicenseDbClassifications.kt
The issue has been fixed upstream and the update has been published, see https://scancode-licensedb.aboutcode.org/ms-cla.json.
Keep the mechanism to make it easy to override categories in the future. Also there may arise need to make the override categories configurable in the future which means there is likely need for this mechanism.
> fix(tool/curations): Drop an obsolete category override entry

- license-classifications.yml
The updated content was generated by [1].
[1] ./gradlew generateLicenseClassifications
> Re-generate license classifications

- curations/Maven/org.jetbrains.kotlin/kotlin-test-js-runner.yml
See [1] for the start of the range.
[1]: https://github.com/JetBrains/kotlin/tree/1.4.0/libraries/tools/kotlin-test-js-runner
> feat(curations): Add VCS path curation for kotlin-test-js-runner

- license-classifications.yml
The updated content was generated by [1].
[1] ./gradlew generateLicenseClassifications
> chore: Re-generate license classifications

- evaluator.rules.kts
A repository configuration or curation within an `.ort.yml` file may be purposeful. This declares a `WARNING` instead of `ERROR` for the evaluator.
Resolves oss-review-toolkit/ort#7753
Please ensure that your pull request adheres to our [contribution guidelines](https://github.com/oss-review-toolkit/.github/blob/main/CONTRIBUTING.md). Thank you!
> chore: Change repo config and curation to warning

- build.gradle.kts
This is required for a transitive dependency of the notifier.
> fix: Add the Atlassian repository

- curations/Maven/com.google.guava/listenablefuture.yml
Also version 1.0 is only "an empty artifact that Guava depends on to signal that it is providing ListenableFuture", "if users want only ListenableFuture, they depend on listenablefuture-1.0", see [1].
[1]: https://mvnrepository.com/artifact/com.google.guava/listenablefuture
> chore: Extend the "listenablefuture" curation to version 1.0

- curations/PyPI/_/packaging.yml
There has been no change on LICENSES for `PyPI::packaging`, which allows us to just increase the version to the current latest number, 23.2.
> chore: Update PyPI::packaging curation to version 23.2

- curations/PyPI/_/mock.yml
The package's metadata data only declares an unspecific "BSD License",
but a closer look at the LICENSE.txt reveals that concretely always
the "BSD-2-Clause" license has been used.
> chore: Add PyPI::mock curation to version 5.1.0

- curations/PyPI/_/python-dateutil.yml
The license of python-dateutil has changed, as it can be seeing
in the curations comment. We are mapping BSD License to to
BSD-3-Clause, and Dual License to `Apache-2.0 AND BSD-3-Clause`
> chore: Add PyPI::python-dateutil curation to version 2.8.2

- curations/Maven/io.netty/netty-all.yml
The same applies to patch-level version 101, and mostly likely to all versions in between from 79.
> chore: Extend the version range of the existing `netty-all` curation

- curations/Maven/antlr/antlr.yml
Version 2.7.7 declares "BSD License" in its POM [1], which is wrong when looking at the `LICENSE.txt` contained in the source artifact. Instead, it is the ANTLR-specific Public Domain license, see [2]
[1]: https://repo1.maven.org/maven2/antlr/antlr/2.7.7/antlr-2.7.7.pom
[2]: https://spdx.org/licenses/ANTLR-PD.html
> fix(antlr): Map "BSD License" to `ANTLR-PD` for version 2.7.7

- license-classifications.yml
- tools/curations/buildSrc/src/main/kotlin/ScanCodeLicenseDbClassifications.kt
> Add some categorizations for GCC exception 3.1

- evaluator.rules.kts
The `-isProject()` condition was missing by accident.
> fix(evaluator.rules): Limit "no license in dependency" rule to pkgs

- curations/Maven/asm/asm.yml
- curations/Maven/org.ow2.asm/asm.yml
Note that never versions are available under the `org.ow2.asm` group, but still lack the SCM tag up to (and including) version 6.0.
> feat(curations): Set VCS info for the Maven `asm` library

- evaluator.rules.kts
For dependency trees made up of large amounts of package references relative to the amount of packages, `packageRule()` executes much faster compared to `dependencyRule()`. So, use `packageRule()` where possible to speed up the execution. For example, projects with large amounts of scopes, typical for Gradle based Android projects, can be evaluated faster.
> perf(evaluator.rules): Consistently prefer package- over dependency rule

- curations/Maven/androidx.hilt/hilt-common.yml
- curations/Maven/androidx.interpolator/interpolator.yml
- curations/Maven/androidx.legacy/legacy-support-core-utils.yml
- curations/Maven/androidx.swiperefreshlayout/swiperefreshlayout.yml
- curations/Maven/org.jetbrains.kotlin/kotlin-android-extensions-runtime.yml
- curations/Maven/org.jetbrains.kotlin/kotlin-annotation-processing-gradle.yml
- curations/Maven/org.jetbrains.kotlin/kotlin-compiler-embeddable.yml
- curations/Maven/org.jetbrains.kotlin/kotlin-daemon-embeddable.yml
- curations/Maven/org.jetbrains.kotlin/kotlin-klib-commonizer-embeddable.yml
- curations/Maven/org.jetbrains.kotlin/kotlin-parcelize-runtime.yml
- curations/Maven/org.jetbrains.kotlin/kotlin-reflect.yml
- curations/Maven/org.jetbrains.kotlin/kotlin-script-runtime.yml
- curations/Maven/org.jetbrains.kotlin/kotlin-stdlib-common.yml
- curations/Maven/org.jetbrains.kotlin/kotlin-stdlib-jdk7.yml
- curations/Maven/org.jetbrains.kotlin/kotlin-stdlib-jdk8.yml
- curations/Maven/org.jetbrains.kotlin/kotlin-stdlib.yml
For these artifacts it's better to scan the source artifact, as VCS provenance would need to be figured out manually which is hard in this case.
> package-curations: Scan source artifacts for some `andriodx` and `kotlin` libs

- curations/PyPI/_/pytest-cov.yml
The library is licensed under MIT, but according to
this [Pull Request](https://github.com/pytest-dev/pytest-cov/pull/467),
the project metadata was mistakenly stating `BSD License`.
All versions below 2.12.0 are impacted by this issue.
Current (4.1.0) license: https://github.com/pytest-dev/pytest-cov/blob/2c9f2170d8575b21bafb6402eb30ca7de31e20b9/LICENSE
Current project metadata: https://github.com/pytest-dev/pytest-cov/blob/2c9f2170d8575b21bafb6402eb30ca7de31e20b9/setup.py
License at 2.12.0: https://github.com/pytest-dev/pytest-cov/blob/9692bad8c3501b77cf950d0732ae9cb5c8bb0bd4/LICENSE
Project metadata at 2.12.0: https://github.com/pytest-dev/pytest-cov/blob/9692bad8c3501b77cf950d0732ae9cb5c8bb0bd4/setup.py
License before 2.12.0: …
> chore: Map a declared license for PyPI::pytest-cov

- package-configurations/Maven/org.apache.commons/commons-compress/1.26.2/vcs.yml
First and foremost, exclude `some-900kb-text.txt` [1] which just contains random text in a single line, which makes ScanCode time out.
Secondly, while at it, also exclude the `.github` build directory committed to VCS.
[1]: https://github.com/apache/commons-compress/blob/rel/commons-compress-1.26.2/src/test/resources/org/apache/commons/compress/COMPRESS-649/some-900kb-text.txt
> feat(package-configurations): Add some path excludes for commons-compress

- curations/Maven/xmlunit/xmlunit.yml
Note that XMLUnit 2.x is hosted at [1].
[1]: https://github.com/xmlunit/xmlunit
> feat(curations): Add a VCS curation for XMLUnit < 2.0

- curations/PyPI/_/tensorflow-intel.yml
FYI @haikoschol, this also has the https://github.com/Intel-tensorflow/tensorflow/tree/v2.12.0 tag.
> feat(curations): Set the VCS info for "PyPI::tensorflow-intel"

- curations/Maven/edu.berkeley.cs.jqf/jqf-fuzz.yml
- curations/Maven/edu.berkeley.cs.jqf/jqf-instrument.yml
- curations/Maven/edu.berkeley.cs.jqf/jqf-maven-plugin.yml
See individual commits for details.
Related to https://github.com/oss-review-toolkit/ort-ci-github-action/issues/40.
> Add various curations for edu.berkeley.cs.jqf packages

- evaluator.rules.kts
A concluded license overrides the applicable license including any declared license. So, do not report issues about the declared license if a concluded license is set.
> feat(evaluator.rules): Improve the unmapped declared license rule

- curations/Maven/com.google.guava/listenablefuture.yml
This reverts commit 7f2f13d as the artifacts in not really metadata-only / empty, but actually contains the `ListenableFuture` interface definition, see [1].
[1]: https://repo1.maven.org/maven2/com/google/guava/listenablefuture/1.0/listenablefuture-1.0-sources.jar
> Revert "chore: Extend the "listenablefuture" curation to version 1.0"

- curations/Maven/xalan/xalan.yml
The tags in the Git repository are confirmed to be associated to versions correctly by ORT.
> feat(curations): Add a VCS curation for Apache Xalan
